# Generated by Django 4.2.5 on 2023-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'banco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.SmallAutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=15)),
                ('segundo_nombre', models.CharField(max_length=15)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.SmallAutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=10)),
                ('monto', models.FloatField()),
                ('id_banco', models.SmallIntegerField(blank=True, null=True)),
                ('id_cliente', models.SmallIntegerField(blank=True, null=True)),
                ('nip', models.CharField(db_column='NIP', max_length=4)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id_operacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('monto', models.FloatField()),
            ],
            options={
                'db_table': 'operacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id_tipo_cuenta', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id_tipo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipo_operacion',
                'managed': False,
            },
        ),
    ]
